import { ElementDefinition } from "./interfaces/ElementDefinition";

export const ELEMENTS: ElementDefinition[] = [
  {
    label: 'Title Bar',
    settings: [
      { label: 'Active Background', section: 'workbench.colorCustomizations', key: 'titleBar.activeBackground', type: 'color' },
      { label: 'Active Foreground', section: 'workbench.colorCustomizations', key: 'titleBar.activeForeground', type: 'color' },
      { label: 'Inactive Background', section: 'workbench.colorCustomizations', key: 'titleBar.inactiveBackground', type: 'color' },
      { label: 'Inactive Foreground', section: 'workbench.colorCustomizations', key: 'titleBar.inactiveForeground', type: 'color' },
      { label: 'Border', section: 'workbench.colorCustomizations', key: 'titleBar.border', type: 'color' },
    ],
  },
  {
    label: 'Activity Bar',
    settings: [
      { label: 'Background', section: 'workbench.colorCustomizations', key: 'activityBar.background', type: 'color' },
      { label: 'Foreground', section: 'workbench.colorCustomizations', key: 'activityBar.foreground', type: 'color' },
      { label: 'Inactive Foreground', section: 'workbench.colorCustomizations', key: 'activityBar.inactiveForeground', type: 'color' },
      { label: 'Border', section: 'workbench.colorCustomizations', key: 'activityBar.border', type: 'color' },
      { label: 'Badge Background', section: 'workbench.colorCustomizations', key: 'activityBarBadge.background', type: 'color' },
      { label: 'Badge Foreground', section: 'workbench.colorCustomizations', key: 'activityBarBadge.foreground', type: 'color' },
      { label: 'Active Border', section: 'workbench.colorCustomizations', key: 'activityBar.activeBorder', type: 'color' },
      { label: 'Active Background', section: 'workbench.colorCustomizations', key: 'activityBar.activeBackground', type: 'color' },
      { label: 'Active Focus Border', section: 'workbench.colorCustomizations', key: 'activityBar.activeFocusBorder', type: 'color' },
      { label: 'Position', section: 'workbench.activityBar', key: 'location', type: 'string', options: ['default', 'top', 'bottom', 'hidden'], description: 'The location of the activity bar. "default" means left in LTR and right in RTL. When positioned at the top or bottom, it becomes part of the sideBar and takes its colors' },
    ],
  },
  {
    label: 'Side Bar',
    settings: [
      { label: 'Background', section: 'workbench.colorCustomizations', key: 'sideBar.background', type: 'color' },
      { label: 'Foreground', section: 'workbench.colorCustomizations', key: 'sideBar.foreground', type: 'color' },
      { label: 'Border', section: 'workbench.colorCustomizations', key: 'sideBar.border', type: 'color' },
      { label: 'Drop Background', section: 'workbench.colorCustomizations', key: 'sideBar.dropBackground', type: 'color' },
      { label: 'Title Foreground', section: 'workbench.colorCustomizations', key: 'sideBarTitle.foreground', type: 'color' },
      { label: 'Section Header Background', section: 'workbench.colorCustomizations', key: 'sideBarSectionHeader.background', type: 'color' },
      { label: 'Section Header Foreground', section: 'workbench.colorCustomizations', key: 'sideBarSectionHeader.foreground', type: 'color' },
      { label: 'Section Header Border', section: 'workbench.colorCustomizations', key: 'sideBarSectionHeader.border', type: 'color' },
      { label: 'Position', section: 'workbench.sideBar', key: 'location', type: 'string', options: ['left', 'right'] },
    ],
  },
  {
    label: 'Command Center',
    settings: [
      { label: 'Foreground', section: 'workbench.colorCustomizations', key: 'commandCenter.foreground', type: 'color' },
      { label: 'Active Foreground', section: 'workbench.colorCustomizations', key: 'commandCenter.activeForeground', type: 'color' },
      { label: 'Background', section: 'workbench.colorCustomizations', key: 'commandCenter.background', type: 'color' },
      { label: 'Active Background', section: 'workbench.colorCustomizations', key: 'commandCenter.activeBackground', type: 'color' },
      { label: 'Border', section: 'workbench.colorCustomizations', key: 'commandCenter.border', type: 'color' },
      { label: 'Inactive Foreground', section: 'workbench.colorCustomizations', key: 'commandCenter.inactiveForeground', type: 'color' },
      { label: 'Inactive Border', section: 'workbench.colorCustomizations', key: 'commandCenter.inactiveBorder', type: 'color' },
      { label: 'Active Border', section: 'workbench.colorCustomizations', key: 'commandCenter.activeBorder', type: 'color' },
      { label: 'Debugging Background', section: 'workbench.colorCustomizations', key: 'commandCenter.debuggingBackground', type: 'color' },
    ],
  },
  {
    label: 'Editor',
    settings: [
      { label: 'Background', section: 'workbench.colorCustomizations', key: 'editor.background', type: 'color' },
      { label: 'Foreground', section: 'workbench.colorCustomizations', key: 'editor.foreground', type: 'color' },
      { label: 'Font Size', section: 'editor', key: 'fontSize', type: 'number', description: 'Editor font size in px' },
      { label: 'Line Number Foreground', section: 'workbench.colorCustomizations', key: 'editorLineNumber.foreground', type: 'color' },
      { label: 'Line Number Active Foreground', section: 'workbench.colorCustomizations', key: 'editorLineNumber.activeForeground', type: 'color' },
      { label: 'Cursor Foreground', section: 'workbench.colorCustomizations', key: 'editorCursor.foreground', type: 'color' },
      { label: 'Selection Background', section: 'workbench.colorCustomizations', key: 'editor.selectionBackground', type: 'color' },
      { label: 'Selection Foreground', section: 'workbench.colorCustomizations', key: 'editor.selectionForeground', type: 'color' },
      { label: 'Inactive Selection Background', section: 'workbench.colorCustomizations', key: 'editor.inactiveSelectionBackground', type: 'color' },
      { label: 'Word Highlight Background', section: 'workbench.colorCustomizations', key: 'editor.wordHighlightBackground', type: 'color' },
      { label: 'Word Highlight Border', section: 'workbench.colorCustomizations', key: 'editor.wordHighlightBorder', type: 'color' },
      { label: 'Find Match Background', section: 'workbench.colorCustomizations', key: 'editor.findMatchBackground', type: 'color' },
      { label: 'Find Match Border', section: 'workbench.colorCustomizations', key: 'editor.findMatchBorder', type: 'color' },
      { label: 'Hover Highlight Background', section: 'workbench.colorCustomizations', key: 'editor.hoverHighlightBackground', type: 'color' },
      { label: 'Line Highlight Background', section: 'workbench.colorCustomizations', key: 'editor.lineHighlightBackground', type: 'color' },
      { label: 'Line Highlight Border', section: 'workbench.colorCustomizations', key: 'editor.lineHighlightBorder', type: 'color' },
    ],
  },
  {
    label: 'Status Bar',
    settings: [
      { label: 'Background', section: 'workbench.colorCustomizations', key: 'statusBar.background', type: 'color' },
      { label: 'Foreground', section: 'workbench.colorCustomizations', key: 'statusBar.foreground', type: 'color' },
      { label: 'Border', section: 'workbench.colorCustomizations', key: 'statusBar.border', type: 'color' },
      { label: 'No Folder Background', section: 'workbench.colorCustomizations', key: 'statusBar.noFolderBackground', type: 'color' },
      { label: 'No Folder Foreground', section: 'workbench.colorCustomizations', key: 'statusBar.noFolderForeground', type: 'color' },
      { label: 'Debugging Background', section: 'workbench.colorCustomizations', key: 'statusBar.debuggingBackground', type: 'color' },
      { label: 'Debugging Foreground', section: 'workbench.colorCustomizations', key: 'statusBar.debuggingForeground', type: 'color' },
      { label: 'Item Active Background', section: 'workbench.colorCustomizations', key: 'statusBarItem.activeBackground', type: 'color' },
      { label: 'Item Hover Background', section: 'workbench.colorCustomizations', key: 'statusBarItem.hoverBackground', type: 'color' },
      { label: 'Item Prominent Background', section: 'workbench.colorCustomizations', key: 'statusBarItem.prominentBackground', type: 'color' },
      { label: 'Item Prominent Foreground', section: 'workbench.colorCustomizations', key: 'statusBarItem.prominentForeground', type: 'color' },
    ],
  },
  {
    label: 'Panel',
    settings: [
      { label: 'Background', section: 'workbench.colorCustomizations', key: 'panel.background', type: 'color' },
      { label: 'Foreground', section: 'workbench.colorCustomizations', key: 'panel.foreground', type: 'color' },
      { label: 'Border', section: 'workbench.colorCustomizations', key: 'panel.border', type: 'color' },
      { label: 'Title Active Border', section: 'workbench.colorCustomizations', key: 'panelTitle.activeBorder', type: 'color' },
      { label: 'Title Active Foreground', section: 'workbench.colorCustomizations', key: 'panelTitle.activeForeground', type: 'color' },
      { label: 'Title Inactive Foreground', section: 'workbench.colorCustomizations', key: 'panelTitle.inactiveForeground', type: 'color' },
      { label: 'Drop Border', section: 'workbench.colorCustomizations', key: 'panel.dropBorder', type: 'color' },
    ],
  },
  {
    label: 'Tabs',
    settings: [
      { label: 'Active Background', section: 'workbench.colorCustomizations', key: 'tab.activeBackground', type: 'color' },
      { label: 'Active Foreground', section: 'workbench.colorCustomizations', key: 'tab.activeForeground', type: 'color' },
      { label: 'Inactive Background', section: 'workbench.colorCustomizations', key: 'tab.inactiveBackground', type: 'color' },
      { label: 'Inactive Foreground', section: 'workbench.colorCustomizations', key: 'tab.inactiveForeground', type: 'color' },
      { label: 'Active Border', section: 'workbench.colorCustomizations', key: 'tab.activeBorder', type: 'color' },
      { label: 'Inactive Modified Border', section: 'workbench.colorCustomizations', key: 'tab.inactiveModifiedBorder', type: 'color' },
      { label: 'Active Modified Border', section: 'workbench.colorCustomizations', key: 'tab.activeModifiedBorder', type: 'color' },
      { label: 'Unfocused Active Background', section: 'workbench.colorCustomizations', key: 'tab.unfocusedActiveBackground', type: 'color' },
      { label: 'Unfocused Active Foreground', section: 'workbench.colorCustomizations', key: 'tab.unfocusedActiveForeground', type: 'color' },
      { label: 'Unfocused Inactive Background', section: 'workbench.colorCustomizations', key: 'tab.unfocusedInactiveBackground', type: 'color' },
      { label: 'Unfocused Inactive Foreground', section: 'workbench.colorCustomizations', key: 'tab.unfocusedInactiveForeground', type: 'color' },
    ],
  },
  {
    label: 'Minimap',
    settings: [
      { label: 'Background', section: 'workbench.colorCustomizations', key: 'minimap.background', type: 'color' },
      { label: 'Selection Highlight', section: 'workbench.colorCustomizations', key: 'minimap.selectionHighlight', type: 'color', description: 'Color of the selection highlight in the minimap. The color must not be opaque so that the underlying content can shine through.' },
      { label: 'Error Highlight', section: 'workbench.colorCustomizations', key: 'minimap.errorHighlight', type: 'color' },
      { label: 'Warning Highlight', section: 'workbench.colorCustomizations', key: 'minimap.warningHighlight', type: 'color' },
      { label: 'Find Match Highlight', section: 'workbench.colorCustomizations', key: 'minimap.findMatchHighlight', type: 'color' },
      { label: 'Gutter Added Background', section: 'workbench.colorCustomizations', key: 'minimapGutter.addedBackground', type: 'color' },
      { label: 'Gutter Modified Background', section: 'workbench.colorCustomizations', key: 'minimapGutter.modifiedBackground', type: 'color' },
      { label: 'Gutter Deleted Background', section: 'workbench.colorCustomizations', key: 'minimapGutter.deletedBackground', type: 'color' },
    ],
  },
  {
    label: 'Progress Bar',
    settings: [
      { label: 'Background', section: 'workbench.colorCustomizations', key: 'progressBar.background', type: 'color' },
    ],
  },
];
